.catalog:
  name: Zookeeper Cluster
  version: zookeeper-3.4.6
  description: |
    Apache Zookeeper cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "Pawan Kumar <monu.pawan@gmail.com>"
  uuid: zk-0
  questions:
    - variable: "zk_scale"
      description: "Number of zk nodes. Note: Recommended an odd number"
      label: "Zk Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "zk_mem"
      description: "Amount of memory to config zk."
      label: "Zk Memory (mb):"
      required: true
      default: 2048 
      type: "string"
    - variable: "zk_interval"
      description: "Interval to poll/apply configuration changes. 0 to disable, reconfiguration will be done when you restart zk nodes"
      label: "Zk Interval (s):"
      required: true
      default: 60
      type: "int"
zk:
 scale: ${zk_scale}
